default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/elektra_db_dev.sqlite3

test:
  <<: *default
  database: db/elektra_db_test.sqlite3

production:
  <<: *default
  database: db/elektra_db.sqlite3
